import PIL
from PIL import ImageTk,Image,ImageGrab
import tkinter
import tkinter.font as font
from tkinter import filedialog,colorchooser,ttk,messagebox
from tkinter.filedialog import askopenfilename,asksaveasfilename
import btnhover
import runpy
from os.path import basename

class collage:
    
    def goback(self):
        self.collagescreen.destroy()
        self.templatelist()
    def goback2(self):
        self.templist.destroy()
        runpy.run_path(path_name='PhotoEditor.py')
        
    def save_collage(self):
        try:
            file=asksaveasfilename(filetypes=[("All Files","*.*"),("PNG file","*.png"),("jpg file","*.jpg")])
            self.finalcollage.save(file)
        except ValueError:
            messagebox.showerror('Error', 'Enter correct Extention')
        except:
            messagebox.showerror('Error', 'Please enter all images properly')
            
    def choose_color(self):
        global color
        color= colorchooser.askcolor(title ="Choose color")
        self.colorbox.configure(bg=color[1])
    def takeimg(self,n,txt):    
        self.imgs[n] = filedialog.askopenfilename(filetypes=[("Image File","*.jpg"),("Image File","*.png")])
        txt.config(text=basename(self.imgs[n]))
        
    def createcollage1(self):
        def create(n1,n2,n3,n4):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((500,500))
                img2 = PIL.Image.open(self.imgs[n2]).resize((500,500))
                img3 = PIL.Image.open(self.imgs[n3]).resize((500,500))
                img4 = PIL.Image.open(self.imgs[n4]).resize((500,500))
                new = Image.new("RGBA", (1030,1030),color[1])
                new.paste(img1,box=(10,10))
                new.paste(img2,box=(520,10))
                new.paste(img3,box=(10,520))
                new.paste(img4,box=(520,520))
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        colorbtn = tkinter.Button(buttonswidget, text = "Select color",command = lambda:self.choose_color())
        colorbtn.grid(row=0,column=0)
        self.colorbox = tkinter.Canvas(buttonswidget, width="20", height="20",relief='groove',bg='black')
        self.colorbox.grid(row=0,column=1,padx=10)
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3))
        createbtn.grid(row=5,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=5,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=6,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
        
    def createcollage2(self):
        def create(n1,n2,n3,n4,n5,n6):
            img1 = PIL.Image.open(self.imgs[n1]).resize((500,500))
            img2 = PIL.Image.open(self.imgs[n2]).resize((500,500))
            img3 = PIL.Image.open(self.imgs[n3]).resize((500,500))
            img4 = PIL.Image.open(self.imgs[n4]).resize((500,500))
            img5 = PIL.Image.open(self.imgs[n5]).resize((500,500))
            img6 = PIL.Image.open(self.imgs[n6]).resize((500,500))
            new = Image.new("RGBA", (1030,1540),color[1])
            new.paste(img1,box=(10,10))
            new.paste(img2,box=(520,10))
            new.paste(img3,box=(10,520))
            new.paste(img4,box=(520,520))
            new.paste(img5,box=(10,1030))
            new.paste(img6,box=(520,1030))
            new.thumbnail((900,900))
            self.finalcollage=new
            collage = ImageTk.PhotoImage(new)
            w1,h1=new.size
            display.configure(width=w1,height=h1)
            display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
            display.image=collage            
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
#------------------------------------------------------------->




        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        colorbtn = tkinter.Button(buttonswidget, text = "Select color",command = lambda:self.choose_color())
        colorbtn.grid(row=0,column=0)
        self.colorbox = tkinter.Canvas(buttonswidget, width="20", height="20",relief='groove',bg='black')
        self.colorbox.grid(row=0,column=1,padx=10)
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        tb6=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb6.grid(row=6,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        imgb6=tkinter.Button(buttonswidget,width=10,text="image 6",command=lambda:self.takeimg(5,tb6))
        imgb6.grid(row=6,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4,5))
        createbtn.grid(row=7,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=7,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=8,column=0,pady=50,padx=20)
        
        self.collagescreen.mainloop()
    
    def createcollage3(self):
        def create(n1,n2,n3,n4,n5):
            img1 = PIL.Image.open(self.imgs[n1]).resize((480,480))
            img2 = PIL.Image.open(self.imgs[n2]).resize((480,480))
            img3 = PIL.Image.open(self.imgs[n3]).resize((480,480))
            img4 = PIL.Image.open(self.imgs[n4]).resize((480,480))
            img5 = PIL.Image.open(self.imgs[n5]).resize((480,480))
            new= PIL.Image.open(r'collage/frame2.png')
            frame=PIL.Image.open(r'collage/frame2_1.png')
            new.paste(img1,box=(40,40))
            new.paste(img2,box=(560,40))
            new.paste(img3,box=(40,560))
            new.paste(img4,box=(560,560))
            new.paste(frame,box=(260,260))
            new.paste(img5,box=(300,300))
            new.thumbnail((900,900))
            self.finalcollage=new
            collage = ImageTk.PhotoImage(new)
            w1,h1=new.size
            display.configure(width=w1,height=h1)
            display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
            display.image=collage            
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4))
        createbtn.grid(row=7,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=7,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=8,column=0,pady=50,padx=20)
        
        self.collagescreen.mainloop()
    
    def createcollage4(self):
        def create(n1,n2,n3,n4,n5,n6):
            img1 = PIL.Image.open(self.imgs[n1]).resize((213,196))
            img2 = PIL.Image.open(self.imgs[n2]).resize((213,196))
            img3 = PIL.Image.open(self.imgs[n3]).resize((213,196))
            img4 = PIL.Image.open(self.imgs[n4]).resize((213,196))
            img5 = PIL.Image.open(self.imgs[n5]).resize((213,196))
            img6 = PIL.Image.open(self.imgs[n6]).resize((436,400))
            new = PIL.Image.open(r'collage/frame3.png')
            new.paste(img1,box=(18,19))
            new.paste(img2,box=(255,19))
            new.paste(img3,box=(492,19))
            new.paste(img4,box=(18,241))
            new.paste(img5,box=(18,463))
            new.paste(img6,box=(262,250))
            new.thumbnail((900,900))
            self.finalcollage=new
            collage = ImageTk.PhotoImage(new)
            w1,h1=new.size
            display.configure(width=w1,height=h1)
            display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
            display.image=collage            
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        tb6=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb6.grid(row=6,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        imgb6=tkinter.Button(buttonswidget,width=10,text="image 6",command=lambda:self.takeimg(5,tb6))
        imgb6.grid(row=6,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4,5))
        createbtn.grid(row=7,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=7,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=8,column=0,pady=50,padx=20)
        
        self.collagescreen.mainloop()
        
    def createcollage5(self):
        def create(n1,n2,n3,n4,n5):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((390,330))
                img2 = PIL.Image.open(self.imgs[n2]).resize((240,330))
                img3 = PIL.Image.open(self.imgs[n3]).resize((255,245))
                img4 = PIL.Image.open(self.imgs[n4]).resize((255,245))
                img5 = PIL.Image.open(self.imgs[n5]).resize((375,505))
                new = Image.new("RGBA", (700,904),color[1])
                new.paste(img1,box=(25,25))
                new.paste(img2,box=(425,25))
                new.paste(img3,box=(25,370))
                new.paste(img4,box=(25,630))
                new.paste(img5,box=(290,370))
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        colorbtn = tkinter.Button(buttonswidget, text = "Select color",command = lambda:self.choose_color())
        colorbtn.grid(row=0,column=0)
        self.colorbox = tkinter.Canvas(buttonswidget, width="20", height="20",relief='groove',bg='black')
        self.colorbox.grid(row=0,column=1,padx=10)
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4))
        createbtn.grid(row=6,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=6,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=7,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
    
    def createcollage6(self):
        def create(n1,n2,n3,n4,n5,n6,n7):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((219,189))
                img2 = PIL.Image.open(self.imgs[n2]).resize((219,189))
                img3 = PIL.Image.open(self.imgs[n3]).resize((219,189))
                img4 = PIL.Image.open(self.imgs[n4]).resize((219,189))
                img5 = PIL.Image.open(self.imgs[n5]).resize((219,189))
                img6 = PIL.Image.open(self.imgs[n6]).resize((219,189))
                img7 = PIL.Image.open(self.imgs[n7]).resize((219,189))
                new = Image.new("RGBA", (850,607),'white')
                new.paste(img1,box=(314,16))
                new.paste(img2,box=(145,111))
                new.paste(img3,box=(483,112))
                new.paste(img4,box=(313,210))
                new.paste(img5,box=(143,306))
                new.paste(img6,box=(483,307))
                new.paste(img7,box=(312,405))
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        tb6=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb6.grid(row=6,column=1,pady=20,padx=20)
        tb7=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb7.grid(row=7,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        imgb6=tkinter.Button(buttonswidget,width=10,text="image 6",command=lambda:self.takeimg(5,tb6))
        imgb6.grid(row=6,column=0,pady=20,padx=20)
        imgb7=tkinter.Button(buttonswidget,width=10,text="image 7",command=lambda:self.takeimg(6,tb7))
        imgb7.grid(row=7,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4,5,6))
        createbtn.grid(row=8,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=8,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=9,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
    
    def createcollage7(self):
        def create(n1,n2,n3,n4,n5,n6,n7,n8):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((181,131))
                img2 = PIL.Image.open(self.imgs[n2]).resize((291,230))
                img3 = PIL.Image.open(self.imgs[n3]).resize((175,155))
                img4 = PIL.Image.open(self.imgs[n4]).resize((279,156))
                img5 = PIL.Image.open(self.imgs[n5]).resize((227,154))
                img6 = PIL.Image.open(self.imgs[n6]).resize((394,392))
                img7 = PIL.Image.open(self.imgs[n7]).resize((223,154))
                img8 = PIL.Image.open(self.imgs[n8]).resize((280,212))
                new = Image.new("RGBA", (1139,740),'white')
                new.paste(img1,box=(203,146))
                new.paste(img2,box=(409,47))
                new.paste(img3,box=(723,122))
                new.paste(img4,box=(64,300))
                new.paste(img5,box=(116,480))
                new.paste(img6,box=(368,301))
                new.paste(img7,box=(784,301))
                new.paste(img8,box=(784,480))
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        tb6=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb6.grid(row=6,column=1,pady=20,padx=20)
        tb7=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb7.grid(row=7,column=1,pady=20,padx=20)
        tb8=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb8.grid(row=8,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        imgb6=tkinter.Button(buttonswidget,width=10,text="image 6",command=lambda:self.takeimg(5,tb6))
        imgb6.grid(row=6,column=0,pady=20,padx=20)
        imgb7=tkinter.Button(buttonswidget,width=10,text="image 7",command=lambda:self.takeimg(6,tb7))
        imgb7.grid(row=7,column=0,pady=20,padx=20)
        imgb8=tkinter.Button(buttonswidget,width=10,text="image 8",command=lambda:self.takeimg(7,tb8))
        imgb8.grid(row=8,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4,5,6,7))
        createbtn.grid(row=9,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=9,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=10,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
    
    def createcollage8(self):
        def create(n1,n2,n3,n4,n5,n6,n7):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((165,277))
                img2 = PIL.Image.open(self.imgs[n2]).resize((258,106))
                img3 = PIL.Image.open(self.imgs[n3]).resize((255,145))
                img4 = PIL.Image.open(self.imgs[n4]).resize((173,277))
                img5 = PIL.Image.open(self.imgs[n5]).resize((173,203))
                img6 = PIL.Image.open(self.imgs[n6]).resize((262,197))
                img7 = PIL.Image.open(self.imgs[n7]).resize((174,197))
                new = Image.new("RGBA", (700,557))
                frame = PIL.Image.open(r'collage/frame8.png')
                new.paste(img1,box=(28,29))
                new.paste(img2,box=(219,29))
                new.paste(img3,box=(221,161))
                new.paste(img4,box=(505,28))
                new.paste(img5,box=(23,328))
                new.paste(img6,box=(215,333))
                new.paste(img7,box=(504,333))
                new.alpha_composite(frame)
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        tb6=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb6.grid(row=6,column=1,pady=20,padx=20)
        tb7=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb7.grid(row=7,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        imgb6=tkinter.Button(buttonswidget,width=10,text="image 6",command=lambda:self.takeimg(5,tb6))
        imgb6.grid(row=6,column=0,pady=20,padx=20)
        imgb7=tkinter.Button(buttonswidget,width=10,text="image 7",command=lambda:self.takeimg(6,tb7))
        imgb7.grid(row=7,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4,5,6))
        createbtn.grid(row=8,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=8,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=9,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
    
    def createcollage9(self):
        def create(n1,n2,n3,n4,n5):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((170,107))
                img2 = PIL.Image.open(self.imgs[n2]).resize((168,108))
                img3 = PIL.Image.open(self.imgs[n3]).resize((252,179))
                img4 = PIL.Image.open(self.imgs[n4]).resize((160,107))
                img5 = PIL.Image.open(self.imgs[n5]).resize((168,105))
                new = Image.new("RGBA", (700,500),'white')
                frame = PIL.Image.open(r'collage/frame9.png')
                new.paste(img1,box=(266,44))
                new.paste(img2,box=(45,196))
                new.paste(img3,box=(226,161))
                new.paste(img4,box=(498,197))
                new.paste(img5,box=(267,349))
                new.alpha_composite(frame)
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4))
        createbtn.grid(row=8,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=8,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=9,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
    
    def createcollage10(self):
        def create(n1,n2,n3,n4,n5):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((204,177))
                img2 = PIL.Image.open(self.imgs[n2]).resize((98,125))
                img3 = PIL.Image.open(self.imgs[n3]).resize((210,178))
                img4 = PIL.Image.open(self.imgs[n4]).resize((99,126))
                img5 = PIL.Image.open(self.imgs[n5]).resize((209,124))
                new = Image.new("RGBA", (700,525),'white')
                frame = PIL.Image.open(r'collage/frame10.png')
                new.paste(img1,box=(125,69))
                new.paste(img2,box=(91,221))
                new.paste(img3,box=(275,187))
                new.paste(img4,box=(443,95))
                new.paste(img5,box=(408,332))
                new.alpha_composite(frame)
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4))
        createbtn.grid(row=8,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=8,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=9,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
    
    def createcollage11(self):
        def create(n1,n2,n3,n4,n5,n6,n7):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((158,135))
                img2 = PIL.Image.open(self.imgs[n2]).resize((180,134))
                img3 = PIL.Image.open(self.imgs[n3]).resize((203,156))
                img4 = PIL.Image.open(self.imgs[n4]).resize((179,134))
                img5 = PIL.Image.open(self.imgs[n5]).resize((135,180))
                img6 = PIL.Image.open(self.imgs[n6]).resize((155,154))
                img7 = PIL.Image.open(self.imgs[n7]).resize((200,135))
                new = Image.new("RGBA", (1000,960))
                frame = PIL.Image.open(r'collage/frame11.png')
                new.paste(frame,box=(0,0))
                new.paste(img1,box=(302,125)) 
                new.paste(img2,box=(226,289)) 
                new.paste(img3,box=(125,455)) 
                new.paste(img4,box=(491,194)) 
                new.paste(img5,box=(507,363)) 
                new.paste(img6,box=(706,261)) 
                new.paste(img7,box=(693,453)) 
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        tb6=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb6.grid(row=6,column=1,pady=20,padx=20)
        tb7=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb7.grid(row=7,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        imgb6=tkinter.Button(buttonswidget,width=10,text="image 6",command=lambda:self.takeimg(5,tb6))
        imgb6.grid(row=6,column=0,pady=20,padx=20)
        imgb7=tkinter.Button(buttonswidget,width=10,text="image 7",command=lambda:self.takeimg(6,tb7))
        imgb7.grid(row=7,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4,5,6))
        createbtn.grid(row=8,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=8,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=9,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
        
    def createcollage12(self):
        def create(n1,n2,n3,n4,n5,n6,n7,n8):
            try:
                img1 = PIL.Image.open(self.imgs[n1]).resize((105,105))
                img2 = PIL.Image.open(self.imgs[n2]).resize((105,105))
                img3 = PIL.Image.open(self.imgs[n3]).resize((234,308))
                img4 = PIL.Image.open(self.imgs[n4]).resize((235,309))
                img5 = PIL.Image.open(self.imgs[n5]).resize((105,104))
                img6 = PIL.Image.open(self.imgs[n6]).resize((105,104))
                img7 = PIL.Image.open(self.imgs[n7]).resize((203,203))
                img8 = PIL.Image.open(self.imgs[n8]).resize((203,203))
                new =  PIL.Image.open(r'collage/frame12.png')
                new.paste(img1,box=(141,143))#246,248
                new.paste(img2,box=(304,143))#409,248
                new.paste(img3,box=(158,304))#392,612
                new.paste(img4,box=(482,158))#717,467
                new.paste(img5,box=(465,524))#570,628
                new.paste(img6,box=(627,524))#732,628
                new.paste(img7,box=(805,152))#1008,355
                new.paste(img8,box=(805,415))#1008,619
                new.thumbnail((900,900))
                self.finalcollage=new
                collage = ImageTk.PhotoImage(new)
                w1,h1=new.size
                display.configure(width=w1,height=h1)
                display.create_image((w1/2)+1.5,(h1/2)+1.5,image=collage)
                display.image=collage
            except:
                 messagebox.showerror('Error', 'Please enter all images properly')
  
        self.templist.destroy()
        self.collagescreen=tkinter.Tk()
        self.collagescreen.title("Create Collage")
        #self.collagescreen.geometry('1320x920')
        self.collagescreen.attributes('-fullscreen', True)
        self.collagescreen.resizable(True,True)
        self.collagescreen.config(bg='#383838')
        self.collagescreen.iconbitmap('res/icon.ico')
        display = tkinter.Canvas(self.collagescreen, width="900", height="900",relief='raised',bg='#383838')      
        display.grid(row=0,column=0)
        buttonswidget=tkinter.Frame(self.collagescreen,padx=10, pady=100,bg="#383838")
        buttonswidget.grid(row=0,column=1,sticky="nswe")
        
        tb1=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb1.grid(row=1,column=1,pady=20,padx=20)
        tb2=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb2.grid(row=2,column=1,pady=20,padx=20)
        tb3=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb3.grid(row=3,column=1,pady=20,padx=20)
        tb4=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb4.grid(row=4,column=1,pady=20,padx=20)
        tb5=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb5.grid(row=5,column=1,pady=20,padx=20)
        tb6=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb6.grid(row=6,column=1,pady=20,padx=20)
        tb7=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb7.grid(row=7,column=1,pady=20,padx=20)
        tb8=tkinter.Label(buttonswidget,width=10,text="",bg='#383838',fg='white')
        tb8.grid(row=8,column=1,pady=20,padx=20)
        
        imgb1=tkinter.Button(buttonswidget,width=10,text="image 1",command=lambda:self.takeimg(0,tb1))
        imgb1.grid(row=1,column=0,pady=20,padx=20)
        imgb2=tkinter.Button(buttonswidget,width=10,text="image 2",command=lambda:self.takeimg(1,tb2))
        imgb2.grid(row=2,column=0,pady=20,padx=20)
        imgb3=tkinter.Button(buttonswidget,width=10,text="image 3",command=lambda:self.takeimg(2,tb3))
        imgb3.grid(row=3,column=0,pady=20,padx=20)
        imgb4=tkinter.Button(buttonswidget,width=10,text="image 4",command=lambda:self.takeimg(3,tb4))
        imgb4.grid(row=4,column=0,pady=20,padx=20)
        imgb5=tkinter.Button(buttonswidget,width=10,text="image 5",command=lambda:self.takeimg(4,tb5))
        imgb5.grid(row=5,column=0,pady=20,padx=20)
        imgb6=tkinter.Button(buttonswidget,width=10,text="image 6",command=lambda:self.takeimg(5,tb6))
        imgb6.grid(row=6,column=0,pady=20,padx=20)
        imgb7=tkinter.Button(buttonswidget,width=10,text="image 7",command=lambda:self.takeimg(6,tb7))
        imgb7.grid(row=7,column=0,pady=20,padx=20)
        imgb8=tkinter.Button(buttonswidget,width=10,text="image 8",command=lambda:self.takeimg(7,tb8))
        imgb8.grid(row=8,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="CREATE",command=lambda:create(0,1,2,3,4,5,6,7))
        createbtn.grid(row=9,column=0,pady=20,padx=20)
        createbtn=tkinter.Button(buttonswidget,width=15,text="SAVE",command=lambda:self.save_collage())
        createbtn.grid(row=9,column=1,pady=20,padx=20)
        backbtn=tkinter.Button(buttonswidget,width=20,text="BACK",command=lambda:self.goback())
        backbtn.grid(row=10,column=0,pady=50,padx=20)
        self.collagescreen.mainloop()
    
    def donothing(self):
        a=0
    def templatelist(self):
        self.imgs=['','','','','','','','','','','','']
        self.finalcollage=''
        self.templist = tkinter.Tk()
        self.templist.title("Collage")
        #self.templist.geometry('1320x920')
        self.templist.attributes('-fullscreen', True)
        self.templist.resizable(True,True)
        self.templist.config(bg='#383838')
        self.templist.iconbitmap('res/icon.ico')
        self.templist.columnconfigure(index=0, weight=1)
        self.templist.columnconfigure(index=1, weight=1)
        self.templist.columnconfigure(index=2, weight=1)
        self.templist.resizable(False, False)
        empty = tkinter.PhotoImage(file = r"res/empty.png")
        empty = empty.subsample(2, 2)
        t1 = tkinter.PhotoImage(file = r"res/template1.png")
        t1 = t1.subsample(2, 2)
        t2 = tkinter.PhotoImage(file = r"res/template2.png")
        t2 = t2.subsample(2, 2)
        t3 = tkinter.PhotoImage(file = r"res/template3.png")
        t3 = t3.subsample(2, 2)
        t4 = tkinter.PhotoImage(file = r"res/template4.png")
        t4 = t4.subsample(2, 2)
        t5 = tkinter.PhotoImage(file = r"res/template5.png")
        t5 = t5.subsample(2, 2)
        t6 = tkinter.PhotoImage(file = r"res/template6.png")
        t6 = t6.subsample(2, 2)
        t7 = tkinter.PhotoImage(file = r"res/template7.png")
        t7 = t7.subsample(2, 2)
        t8 = tkinter.PhotoImage(file = r"res/template8.png")
        t8 = t8.subsample(2, 2)
        t9 = tkinter.PhotoImage(file = r"res/template9.png")
        t9 = t9.subsample(2, 2)
        t10 = tkinter.PhotoImage(file = r"res/template10.png")
        t10 = t10.subsample(2, 2)
        t11 = tkinter.PhotoImage(file = r"res/template11.png")
        t11 = t11.subsample(2, 2)
        t12 = tkinter.PhotoImage(file = r"res/template12.png")
        t12 = t12.subsample(2, 2)
        toptext = ttk.Label(self.templist, text="Choose a Template",font=font.Font(family="Fonarto",size=25) ,justify="center",background='#383838',foreground="white")
        toptext.grid(row=0, column=0, pady=50, columnspan=3)
        b1=tkinter.Button(self.templist,background='#383838',image=t1,compound = 'center',relief='ridge',command=lambda:self.createcollage1())
        b1.grid(row=1,column=0)
        b2=tkinter.Button(self.templist,background='#383838',image=t2,compound = 'center',relief='ridge',command=lambda:self.createcollage2())
        b2.grid(row=1,column=1)
        b3=tkinter.Button(self.templist,background='#383838',image=t3,compound = 'center',relief='ridge',command=lambda:self.createcollage3())
        b3.grid(row=1,column=2)
        b4=tkinter.Button(self.templist,background='#383838',image=t4,compound = 'center',relief='ridge',command=lambda:self.createcollage4())
        b4.grid(row=2,column=0)
        b5=tkinter.Button(self.templist,background='#383838',image=t5,compound = 'center',relief='ridge',command=lambda:self.createcollage5())
        b5.grid(row=2,column=1)
        b6=tkinter.Button(self.templist,background='#383838',image=t6,compound = 'center',relief='ridge',command=lambda:self.createcollage6())
        b6.grid(row=2,column=2)
        backbtn=tkinter.Button(self.templist,text="back",compound = 'center',relief='ridge',command=lambda:self.goback2())
        backbtn.grid(row=3,column=0,padx=20,pady=20)
        selectbtn=tkinter.Spinbox(self.templist,from_=1, to=2,state="readonly",font=font.Font(size=36, weight='bold'),width=2,command=lambda:valuechanged())
        selectbtn.grid(row=3,column=1,columnspan=2,padx=20,pady=20)
        
        def valuechanged():
            if(selectbtn.get()=='1'):
                b1=tkinter.Button(self.templist,background='#383838',image=t1,compound = 'center',relief='ridge',command=lambda:self.createcollage1())
                b1.grid(row=1,column=0)
                b2=tkinter.Button(self.templist,background='#383838',image=t2,compound = 'center',relief='ridge',command=lambda:self.createcollage2())
                b2.grid(row=1,column=1)
                b3=tkinter.Button(self.templist,background='#383838',image=t3,compound = 'center',relief='ridge',command=lambda:self.createcollage3())
                b3.grid(row=1,column=2)
                b4=tkinter.Button(self.templist,background='#383838',image=t4,compound = 'center',relief='ridge',command=lambda:self.createcollage4())
                b4.grid(row=2,column=0)
                b5=tkinter.Button(self.templist,background='#383838',image=t5,compound = 'center',relief='ridge',command=lambda:self.createcollage5())
                b5.grid(row=2,column=1)
                b6=tkinter.Button(self.templist,background='#383838',image=t6,compound = 'center',relief='ridge',command=lambda:self.createcollage6())
                b6.grid(row=2,column=2)
            elif(selectbtn.get()=='2'):
                b1=tkinter.Button(self.templist,background='#383838',image=t7,compound = 'center',relief='ridge',command=lambda:self.createcollage7())
                b1.grid(row=1,column=0)
                b2=tkinter.Button(self.templist,background='#383838',image=t8,compound = 'center',relief='ridge',command=lambda:self.createcollage8())
                b2.grid(row=1,column=1)
                b3=tkinter.Button(self.templist,background='#383838',image=t9,compound = 'center',relief='ridge',command=lambda:self.createcollage9())
                b3.grid(row=1,column=2)
                b4=tkinter.Button(self.templist,background='#383838',image=t10,compound = 'center',relief='ridge',command=lambda:self.createcollage10())
                b4.grid(row=2,column=0)
                b5=tkinter.Button(self.templist,background='#383838',image=t11,compound = 'center',relief='ridge',command=lambda:self.createcollage11())
                b5.grid(row=2,column=1)
                b6=tkinter.Button(self.templist,background='#383838',image=t12,compound = 'center',relief='ridge',command=lambda:self.createcollage12())
                b6.grid(row=2,column=2)
                
                
        self.templist.mainloop()

        
    def __init__(self):
        self.templatelist()
        
